import './globals.css';
import { Poppins } from 'next/font/google';
import Provider from './provider';
import Header from '@/components/Header';

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-poppins',
});

export const metadata = {
    title: 'Maulana Ahmad Aji Triadi',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${poppins.variable} font-sans bg-white dark:bg-slate-950`}>
                <Provider>
                    <Header />
                    {children}
                </Provider>
            </body>
        </html>
    );
}
