import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import { ThemeProvider } from './providers';

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-poppins',
});

const dankMono = localFont({
    src: '../fonts/dankmono-regular.otf',
    variable: '--font-dankmono',
});

export const metadata: Metadata = {
    title: 'Maulana Ahmad Aji Triadi - Web Developer',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body
                className={`${poppins.className} ${dankMono.variable} bg-gray-100 dark:bg-gray-900 antialiased`}>
                <ThemeProvider attribute='class'>{children}</ThemeProvider>
            </body>
        </html>
    );
}
